version: '3.8'

services:
    storage:
        container_name: minibank_storage
        image: postgres:14
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: minibank-db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 5788
        volumes:
            - ./minibank-storage:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d minibank-db -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
      
    app:
        container_name: app
        build: 
            context: ./
            dockerfile: ./Minibank.Dockerfile
        depends_on:
            storage:
                condition: service_healthy
        ports: 
            - "5000:5000"
            - "5001:5001"
        environment:
            DataBase__ConnectionString: Host=storage;Port=5432;Database=minibank-db;Username=postgres;Password=5788